import { existsSync, lstatSync, readFileSync, readlinkSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { SourceBindingMode, TreeMode } from "./binding-state.js";
import { ManagedFileAction, upsertWhitepaperFile } from "./skill-lib.js";
import { ensureTrailingNewline } from "./shared.js";

export type SourceIntegrationFile = "AGENTS.md" | "CLAUDE.md";

export type SourceIntegrationUpdate = {
  action: ManagedFileAction;
  file: SourceIntegrationFile;
};

export type SourceIntegrationOptions = {
  bindingMode?: SourceBindingMode;
  entrypoint?: string;
  sourceStatePath?: string;
  treeMode?: TreeMode;
  treeRepoName?: string;
  treeRepoUrl?: string;
  workspaceId?: string;
};

export type GitIgnoreUpdate = {
  action: "created" | "updated" | "unchanged";
  file: ".gitignore";
};

const SOURCE_STATE_FILE = ".first-tree/source.json";
const LOCAL_TREE_TEMP_ROOT = ".first-tree/tmp";
const SOURCE_INTEGRATION_BEGIN = "<!-- BEGIN FIRST-TREE-SOURCE-INTEGRATION -->";
const SOURCE_INTEGRATION_END = "<!-- END FIRST-TREE-SOURCE-INTEGRATION -->";
const SOURCE_INTEGRATION_MARKER = "FIRST-TREE-SOURCE-INTEGRATION:";
const TREE_REPO_MARKER = "FIRST-TREE-TREE-REPO:";
const TREE_MODE_MARKER = "FIRST-TREE-TREE-MODE:";
const BINDING_MODE_MARKER = "FIRST-TREE-BINDING-MODE:";
const TREE_REPO_URL_MARKER = "FIRST-TREE-TREE-REPO-URL:";
const ENTRYPOINT_MARKER = "FIRST-TREE-ENTRYPOINT:";
const WORKSPACE_ID_MARKER = "FIRST-TREE-WORKSPACE-ID:";
const SOURCE_STATE_MARKER = "FIRST-TREE-SOURCE-STATE:";
const SOURCE_INTEGRATION_FILES: readonly SourceIntegrationFile[] = [
  "AGENTS.md",
  "CLAUDE.md",
] as const;

const LOCAL_TREE_GITIGNORE_ENTRIES = [`${LOCAL_TREE_TEMP_ROOT}/`] as const;

export function buildSourceIntegrationBlock(
  treeRepoName: string,
  options?: SourceIntegrationOptions,
): string {
  const details = deriveSourceIntegrationDetails(treeRepoName, options);

  return [
    SOURCE_INTEGRATION_BEGIN,
    "## First Tree integration",
    "",
    "> Managed block — regenerated by `first-tree` tooling. Do not edit by hand.",
    "",
    details.scopeText,
    "",
    "### Binding",
    "",
    ...details.bindingLines,
    "",
    "<!--",
    ...details.metadataLines,
    "-->",
    "",
    "### Before every task",
    "",
    `- Read \`${details.sourceStatePathValue}\` first. Use its recorded tree repo URL and tree repo name as the source of truth for which Context Tree this repo belongs to.`,
    "- If you already have that tree repo cloned locally, update it before you read anything else.",
    details.fallbackInstruction,
    `- Never commit anything under \`${LOCAL_TREE_TEMP_ROOT}/\` to this repo. It is local-only workspace state.`,
    "",
    "### After every task",
    "",
    "- Always ask whether the tree needs updating.",
    "- If the task changed decisions, constraints, rationale, ownership, or shared workspace relationships, open a PR in the tree repo first. Then open the source/workspace code PR.",
    "- If the task changed only implementation details, skip the tree PR and open only the source/workspace code PR.",
    SOURCE_INTEGRATION_END,
  ].join("\n");
}

function deriveSourceIntegrationDetails(
  treeRepoName: string,
  options?: SourceIntegrationOptions,
): {
  bindingLines: string[];
  fallbackInstruction: string;
  metadataLines: string[];
  scopeText: string;
  sourceStatePathValue: string;
} {
  const bindingMode = options?.bindingMode ?? "standalone-source";
  const treeMode = options?.treeMode ?? "dedicated";
  const entrypoint = options?.entrypoint ?? "/";
  const sourceStatePathValue = options?.sourceStatePath ?? SOURCE_STATE_FILE;
  const resolvedTreeRepoName = options?.treeRepoName ?? treeRepoName;
  const treeRepoUrl = options?.treeRepoUrl?.trim() || null;
  const workspaceId = options?.workspaceId?.trim() || null;

  return {
    bindingLines: buildBindingLines(
      resolvedTreeRepoName,
      bindingMode,
      entrypoint,
      workspaceId,
      treeRepoUrl,
      sourceStatePathValue,
    ),
    fallbackInstruction: buildFallbackInstruction(treeRepoName, treeRepoUrl),
    metadataLines: buildMetadataLines(
      treeRepoName,
      resolvedTreeRepoName,
      bindingMode,
      treeMode,
      entrypoint,
      workspaceId,
      treeRepoUrl,
      sourceStatePathValue,
    ),
    scopeText: describeScope(bindingMode, treeMode, treeRepoName, workspaceId),
    sourceStatePathValue,
  };
}

function buildBindingLines(
  resolvedTreeRepoName: string,
  bindingMode: SourceBindingMode,
  entrypoint: string,
  workspaceId: string | null,
  treeRepoUrl: string | null,
  sourceStatePathValue: string,
): string[] {
  return [
    `- **Tree repo:** \`${resolvedTreeRepoName}\``,
    `- **Binding mode:** \`${bindingMode}\``,
    `- **Entrypoint:** \`${entrypoint}\``,
    ...(workspaceId === null ? [] : [`- **Workspace ID:** \`${workspaceId}\``]),
    `- **Tree repo URL:** ${formatTreeRepoUrlDisplay(treeRepoUrl)}`,
    `- **Source state:** \`${sourceStatePathValue}\``,
  ];
}

function buildMetadataLines(
  treeRepoName: string,
  resolvedTreeRepoName: string,
  bindingMode: SourceBindingMode,
  treeMode: TreeMode,
  entrypoint: string,
  workspaceId: string | null,
  treeRepoUrl: string | null,
  sourceStatePathValue: string,
): string[] {
  return [
    `${SOURCE_INTEGRATION_MARKER} ${describeBinding(bindingMode, treeMode, treeRepoName)}`,
    `${TREE_REPO_MARKER} \`${resolvedTreeRepoName}\``,
    `${TREE_MODE_MARKER} \`${treeMode}\``,
    `${BINDING_MODE_MARKER} \`${bindingMode}\``,
    `${TREE_REPO_URL_MARKER} ${treeRepoUrl === null ? "pending publish" : `\`${treeRepoUrl}\``}`,
    `${ENTRYPOINT_MARKER} \`${entrypoint}\``,
    ...(workspaceId === null ? [] : [`${WORKSPACE_ID_MARKER} \`${workspaceId}\``]),
    `${SOURCE_STATE_MARKER} \`${sourceStatePathValue}\``,
  ];
}

function formatTreeRepoUrlDisplay(treeRepoUrl: string | null): string {
  return treeRepoUrl === null ? "_pending publish_" : `<${treeRepoUrl}>`;
}

function buildFallbackInstruction(treeRepoName: string, treeRepoUrl: string | null): string {
  if (treeRepoUrl === null) {
    return "- If the tree has not been published yet, work from the local checkout you just bound (or pass `--tree-path` explicitly) until `first-tree tree publish` records the GitHub repo URL.";
  }

  return `- If you do not already have that tree repo cloned locally, clone a temporary working copy from \`${treeRepoUrl}\` into \`${join(LOCAL_TREE_TEMP_ROOT, treeRepoName)}/\`, use it for the current task, and delete it before you finish.`;
}

function describeBinding(
  bindingMode: SourceBindingMode,
  treeMode: TreeMode,
  treeRepoName: string,
): string {
  switch (bindingMode) {
    case "workspace-root":
      return `workspace root bound to shared tree repo \`${treeRepoName}\``;
    case "workspace-member":
      return `workspace member bound to shared tree repo \`${treeRepoName}\``;
    case "shared-source":
      return `source repo bound to shared tree repo \`${treeRepoName}\``;
    default:
      return treeMode === "shared"
        ? `source repo bound to shared tree repo \`${treeRepoName}\``
        : `source repo bound to dedicated tree repo \`${treeRepoName}\``;
  }
}

function describeScope(
  bindingMode: SourceBindingMode,
  treeMode: TreeMode,
  treeRepoName: string,
  workspaceId: string | null,
): string {
  switch (bindingMode) {
    case "workspace-root":
      return `This folder is a workspace root. Install first-tree locally here, keep all Context Tree files only in the shared \`${treeRepoName}\` repo, and keep child repos bound to the same tree${workspaceId === null ? "" : ` for workspace \`${workspaceId}\``}.`;
    case "workspace-member":
      return `This repo is a workspace member. Keep all Context Tree files only in the shared \`${treeRepoName}\` repo and follow the workspace root's binding for shared context updates${workspaceId === null ? "" : ` in workspace \`${workspaceId}\``}.`;
    case "shared-source":
      return `This repo is bound to an existing shared Context Tree. Keep all Context Tree files only in the shared \`${treeRepoName}\` repo.`;
    default:
      return treeMode === "shared"
        ? `This repo is bound to a shared Context Tree. Keep all Context Tree files only in the shared \`${treeRepoName}\` repo.`
        : `This repo is a source/workspace repo. Keep all Context Tree files only in the dedicated \`${treeRepoName}\` repo.`;
  }
}

export function upsertSourceIntegrationFiles(
  root: string,
  treeRepoName: string,
  options?: SourceIntegrationOptions,
): SourceIntegrationUpdate[] {
  return SOURCE_INTEGRATION_FILES.map((file) =>
    upsertSourceIntegrationFile(root, file, treeRepoName, options),
  );
}

function upsertSourceIntegrationFile(
  root: string,
  file: SourceIntegrationFile,
  treeRepoName: string,
  options?: SourceIntegrationOptions,
): SourceIntegrationUpdate {
  const fullPath = join(root, file);
  const exists = existsSync(fullPath);
  const current = exists ? readFileSync(fullPath, "utf-8") : "";
  const normalized = current.replaceAll("\r\n", "\n");
  const nextBlock = buildSourceIntegrationBlock(
    treeRepoName,
    deriveIntegrationOptions(normalized, treeRepoName, options),
  );
  const nextText = replaceManagedSourceIntegrationBlock(normalized, nextBlock);

  if (ensureTrailingNewline(nextText) === ensureTrailingNewline(normalized)) {
    return { action: "unchanged", file };
  }

  writeFileSync(fullPath, ensureTrailingNewline(nextText));
  return { action: exists ? "updated" : "created", file };
}

function deriveIntegrationOptions(
  normalized: string,
  treeRepoName: string,
  options?: SourceIntegrationOptions,
): SourceIntegrationOptions {
  return {
    bindingMode: firstDefined(options?.bindingMode, detectExistingBindingMode(normalized)),
    entrypoint: firstDefined(options?.entrypoint, detectExistingEntrypoint(normalized)),
    sourceStatePath: firstDefined(
      options?.sourceStatePath,
      detectExistingSourceStatePath(normalized),
      SOURCE_STATE_FILE,
    ),
    treeMode: firstDefined(options?.treeMode, detectExistingTreeMode(normalized)),
    treeRepoName: firstDefined(
      options?.treeRepoName,
      detectExistingTreeRepoName(normalized),
      treeRepoName,
    ),
    treeRepoUrl: firstDefined(options?.treeRepoUrl, detectExistingTreeRepoUrl(normalized)),
    workspaceId: firstDefined(options?.workspaceId, detectExistingWorkspaceId(normalized)),
  };
}

function firstDefined<T>(...values: Array<T | null | undefined>): T | undefined {
  for (const value of values) {
    if (value !== undefined && value !== null) {
      return value;
    }
  }
  return undefined;
}

function replaceManagedSourceIntegrationBlock(normalized: string, nextBlock: string): string {
  const managedBlock =
    /<!-- BEGIN FIRST-TREE-SOURCE-INTEGRATION -->[\s\S]*?<!-- END FIRST-TREE-SOURCE-INTEGRATION -->\n?/mu;
  return managedBlock.test(normalized)
    ? normalized.replace(managedBlock, `${nextBlock}\n`)
    : appendManagedBlock(normalized, nextBlock);
}

function appendManagedBlock(current: string, nextBlock: string): string {
  const trimmed = current.trimEnd();
  if (trimmed.length === 0) {
    return `${nextBlock}\n`;
  }
  return `${trimmed}\n\n${nextBlock}\n`;
}

function detectExistingTreeRepoUrl(text: string): string | null {
  const match = text.match(/^FIRST-TREE-TREE-REPO-URL:\s+`(.+?)`\s*$/mu);
  return match?.[1] ?? null;
}

function detectExistingTreeRepoName(text: string): string | null {
  const explicit = text.match(/^FIRST-TREE-TREE-REPO:\s+`(.+?)`\s*$/mu);
  if (explicit?.[1]) {
    return explicit[1];
  }
  const legacy = text.match(/^FIRST-TREE-SOURCE-INTEGRATION:\s+.*?\b(?:repo|tree)\s+`(.+?)`\s*$/mu);
  return legacy?.[1] ?? null;
}

function detectExistingTreeMode(text: string): TreeMode | null {
  const match = text.match(/^FIRST-TREE-TREE-MODE:\s+`(.+?)`\s*$/mu);
  return match?.[1] === "dedicated" || match?.[1] === "shared" ? match[1] : null;
}

function detectExistingBindingMode(text: string): SourceBindingMode | null {
  const match = text.match(/^FIRST-TREE-BINDING-MODE:\s+`(.+?)`\s*$/mu);
  switch (match?.[1]) {
    case "standalone-source":
    case "shared-source":
    case "workspace-root":
    case "workspace-member":
      return match[1];
    default:
      return null;
  }
}

function detectExistingEntrypoint(text: string): string | null {
  const match = text.match(/^FIRST-TREE-ENTRYPOINT:\s+`(.+?)`\s*$/mu);
  return match?.[1] ?? null;
}

function detectExistingWorkspaceId(text: string): string | null {
  const match = text.match(/^FIRST-TREE-WORKSPACE-ID:\s+`(.+?)`\s*$/mu);
  return match?.[1] ?? null;
}

function detectExistingSourceStatePath(text: string): string | null {
  const match = text.match(/^FIRST-TREE-SOURCE-STATE:\s+`(.+?)`\s*$/mu);
  return match?.[1] ?? null;
}

export function upsertLocalTreeGitIgnore(root: string): GitIgnoreUpdate {
  const fullPath = join(root, ".gitignore");
  const exists = existsSync(fullPath);
  const current = exists ? readFileSync(fullPath, "utf-8") : "";
  const lines = current
    .replaceAll("\r\n", "\n")
    .split("\n")
    .filter((line, index, source) => {
      if (index === source.length - 1 && line === "") {
        return false;
      }
      return true;
    });

  let changed = false;

  for (const entry of LOCAL_TREE_GITIGNORE_ENTRIES) {
    if (!lines.includes(entry)) {
      lines.push(entry);
      changed = true;
    }
  }

  if (!changed) {
    return { action: "unchanged", file: ".gitignore" };
  }

  writeFileSync(fullPath, ensureTrailingNewline(lines.join("\n")));
  return { action: exists ? "updated" : "created", file: ".gitignore" };
}

export function ensureWhitepaperSymlink(root: string): ManagedFileAction {
  return upsertWhitepaperFile(root);
}

export function readManagedWhitepaperTarget(root: string): string | null {
  const fullPath = join(root, "WHITEPAPER.md");
  try {
    const stat = lstatSync(fullPath);
    if (!stat.isSymbolicLink()) {
      return null;
    }
    return readlinkSync(fullPath);
  } catch {
    return null;
  }
}

export function removeManagedWhitepaper(root: string): void {
  const fullPath = join(root, "WHITEPAPER.md");
  if (readManagedWhitepaperTarget(root) !== null) {
    rmSync(fullPath, { force: true });
  }
}
